local M = {}

function M.get()
	return {
		-- colors
		OctoGrey = { fg = C.base },
		OctoBlue = { fg = C.blue },
		OctoGreen = { fg = C.green },
		OctoRed = { fg = C.red },
		OctoPurple = { fg = C.mauve },
		OctoYellow = { fg = C.yellow },
		-- highlight groups
		OctoDirty = { link = "ErrorMsg" },
		OctoIssueTitle = { link = "PreProc" },
		OctoIssueId = { link = "Question" },
		OctoEmpty = { link = "Comment" },
		OctoFloat = { link = "NormalNC" },
		OctoDate = { link = "Comment" },
		OctoSymbol = { link = "Comment" },
		OctoTimelineItemHeading = { link = "Comment" },
		OctoDetailsLabel = { link = "Title" },
		OctoMissingDetails = { link = "Comment" },
		OctoDetailsValue = { link = "Identifier" },
		OctoDiffHunkPosition = { link = "NormalFloat" },
		OctoCommentLine = { link = "TabLineSel" },
		OctoViewer = { fg = C.base, bg = C.blue },
		OctoBubble = { fg = C.text, bg = C.mantle },
		OctoBubbleGrey = { fg = C.text, bg = C.mantle },
		OctoBubbleDelimiterGrey = { fg = C.mantle },
		OctoBubbleGreen = { fg = C.base, bg = C.green },
		OctoBubbleDelimiterGreen = { fg = C.green },
		OctoBubbleBlue = { fg = C.base, bg = C.sky },
		OctoBubbleDelimiterBlue = { fg = C.sky },
		OctoBubbleYellow = { fg = C.base, bg = C.yellow },
		OctoBubbleDelimiterYellow = { fg = C.yellow },
		OctoBubbleRed = { fg = C.base, bg = C.red },
		OctoBubbleDelimiterRed = { fg = C.red },
		OctoBubblePurple = { fg = C.base, bg = C.mauve },
		OctoBubbleDelimiterPurple = { fg = C.mauve },
		OctoUser = { link = "OctoBubble" },
		OctoUserViewer = { link = "OctoViewer" },
		OctoReaction = { link = "OctoBubble" },
		OctoReactionViewer = { link = "OctoViewer" },
		OctoPassingTest = { link = "OctoGreen" },
		OctoFailingTest = { link = "OctoRed" },
		OctoPullAdditions = { link = "OctoGreen" },
		OctoPullDeletions = { link = "OctoRed" },
		OctoPullModifications = { fg = C.peach },
		OctoStateOpen = { fg = C.green, bg = C.mantle },
		OctoStateOpenFloat = { fg = C.green, bg = C.mantle },
		OctoStateClosed = { fg = C.red, bg = C.mantle },
		OctoStateClosedFloat = { fg = C.red, bg = C.mantle },
		OctoStateMerged = { fg = C.mauve, bg = C.mantle },
		OctoStateMergedFloat = { fg = C.mauve, bg = C.mantle },
		OctoStatePending = { fg = C.peach, bg = C.mantle },
		OctoStatePendingFloat = { fg = C.peach, bg = C.mantle },
		OctoStateApproved = { link = "OctoStateOpen" },
		OctoStateApprovedFloat = { link = "OctoStateOpen" },
		OctoStateChangesRequested = { fg = C.maroon, bg = C.mantle },
		OctoStateChangesRequestedFloat = { fg = C.maroon, bg = C.mantle },
		OctoStateCommented = { link = "Normal" },
		OctoStateCommentedFloat = { link = "Normal" },
		OctoStateDismissed = { link = "OctoStateClosed" },
		OctoStateDismissedFloat = { link = "OctoStateClosed" },
		OctoStateSubmittedBubble = { link = "OctoBubbleGreen" },
		OctoFilePanelCounter = { fg = C.blue, style = { "bold" } },
		OctoFilePanelTitle = { fg = C.blue, style = { "bold" } },
		OctoNormalFront = { fg = C.text },
		OctoYellowFloat = { fg = C.yellow, bg = C.mantle },
		OctoPurpleFloat = { fg = C.mauve, bg = C.mantle },
		OctoRedFloat = { fg = C.red, bg = C.mantle },
		OctoGreenFloat = { fg = C.green, bg = C.mantle },
		OctoGreyFloat = { fg = C.text, bg = C.mantle },
		OctoBlueFloat = { fg = C.blue, bg = C.mantle },
	}
end

return M
