name: Generate Integration Table

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'lua/catppuccin/groups/integrations/**.lua'
    branches-ignore:
      - 'release-please*'

jobs:
  docs:
    name: Update integration table
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}
      - name: Install Neovim
        uses: MunifTanjim/setup-neovim-action@v1
        with:
          tag: nightly
      - name: Update integration table
        run: |
          nvim -l scripts/generate_integration_mappings_table.lua
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore: auto generate integration table"
          branch: ${{ github.ref }}
